---
version: '3'

services:
  postgres:
    image: marketplace.gcr.io/google/postgresql13
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    build: .
    volumes:
      - keycloak-data-volume:/opt/keycloak/data
    command: start --optimized
    environment:
        KC_PROXY: edge
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_HOSTNAME_URL: https://<your-domain>
        KC_HOSTNAME_ADMIN_URL: https://<your-domain>
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres
  lb:
    image: nginx
    ports:
     - 80:80
     - 443:443
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/sites-enabled/<your-domain>:/etc/nginx/sites-enabled/<your-domain>:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - /etc/nginx/sites-available/<your-domain>:/etc/nginx/sites-available/<your-domain>:ro
    depends_on:
     - keycloak
volumes:
  postgres-db-volume:
  keycloak-data-volume:
