---
version: '3'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    env_file:
      - default.env
  keycloak:
    build: .
    volumes:
      - keycloak-data-volume:/opt/keycloak/data
    command: start --optimized
    environment:
        KC_PROXY: edge
        KC_HOSTNAME_URL: https://auth.opencdms.org
        KC_HOSTNAME_ADMIN_URL: https://auth.opencdms.org
    env_file:
      - default.env
    ports:
      - 8080:8080
    depends_on:
      - postgres
  nginx:
    image: nginx
    ports:
     - 80:80
     - 443:443
    volumes:
      # To update conf files in containers use `docker compose build --no-cache nginx`
      # To fix, try mounting directory instead of individual files
      - ./auth.opencdms.org.conf:/etc/nginx/conf.d/auth.opencdms.org.conf
      - ./geo.opencdms.org.conf:/etc/nginx/conf.d/geo.opencdms.org.conf
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
     - keycloak
  api:
    container_name: opencdms-api
    build:
      context: ./containers/api/
      dockerfile: Dockerfile
    env_file:
      - default.env
    ports:
      - 5000:5000
    volumes:
      - "./containers/api/config/:/config"
    tty: true
    entrypoint: [ "opencdms", "api", "serve" ]

volumes:
  postgres-db-volume:
  keycloak-data-volume:
