---
version: '3'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: initpassword
  keycloak:
    build: .
    volumes:
      - keycloak-data-volume:/opt/keycloak/data
    command: start --optimized
    environment:
        KC_PROXY: edge
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_HOSTNAME_URL: https://auth.opencdms.org
        KC_HOSTNAME_ADMIN_URL: https://auth.opencdms.org
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: initpassword
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: initpassword
    ports:
      - 8080:8080
    depends_on:
      - postgres
  nginx:
    image: nginx
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/auth.opencdms.org.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
     - keycloak
volumes:
  postgres-db-volume:
  keycloak-data-volume:
